# deployment
prepare-current:
	echo "Make sure that we are the master branch"
	cd $(DeployTarget) && git checkout master && git pull

prepare-ngx13:
	echo "Make sure that we are the ngx13 branch"
	cd $(DeployTarget) && git checkout ngx13 && git pull

prepare-ngx14:
	@echo "--> Ensuring branch 'ngx14' exists and is tracking the remote..."
	cd $(DeployTarget) && \
	(git checkout ngx14 || (git checkout -b ngx14 && git push -u origin ngx14)) && \
	git pull

prepare-ngx15:
	@echo "--> Ensuring branch 'ngx15' exists and is tracking the remote..."
	cd $(DeployTarget) && \
	(git checkout ngx15 || (git checkout -b ngx15 && git push -u origin ngx15)) && \
	git pull

prepare-ngx16:
	@echo "--> Ensuring branch 'ngx16' exists and is tracking the remote..."
	cd $(DeployTarget) && \
	(git checkout ngx16 || (git checkout -b ngx16 && git push -u origin ngx16)) && \
	git pull

prepare-ngx17:
	@echo "--> Ensuring branch 'ngx17' exists and is tracking the remote..."
	cd $(DeployTarget) && \
	(git checkout ngx17 || (git checkout -b ngx17 && git push -u origin ngx17)) && \
	git pull

build:
	echo "Build ..."
	ng build $(BuildTarget)
	echo "Build done"

copy:
	echo "Clean old files ..."
	cd $(DeployTarget) && find . -path ./.git -prune -o -name "README.md" -prune -o -name ".nojekyll" -prune -o -type f -exec rm {} \;
	echo "Clean old files done"
	echo "Copy files ..."
	cp -r $(BuildDist)/* $(DeployTarget)/
	echo "Copy files done"


doc:
	echo "Build doc ..."
	npm run doc
	echo "Build doc done"
	echo "Copy doc ..."
	mkdir -p $(DeployTarget)/docs
	cp -r $(BuildDoc)/* $(DeployTarget)/docs/
	echo "Copy doc done"

push:
	echo "Find new files ..."
	cd $(DeployTarget) && find . -path ./.git -prune -o -name "README.md" -prune -o -type f -exec git add {} \;
	echo "Find new files done"
	echo "Commit ..."
	cd $(DeployTarget) && git commit -am "New publish"
	echo "Commit done ..."
	echo "Push ..."
	cd $(DeployTarget) && git push
	echo "Push done"

deploy: build copy push


.PHONY: build copy push doc deploy
